version: '3.3'
services:
#  nginx:
#    image: nginx:1.10
#    volumes:
#     - ./hosts/docker.local:/etc/nginx/conf.d/docker.local
#     - ./www/docker.local:/var/www/docker.local
#    ports:
#     - "8080:80"
#    environment:
#     - NGINX_HOST=docker.local
#     - NGINX_PORT=80
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/docker.local > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
#
#    links:
#      - php
  web:
      image: nginx:latest
      ports:
          - "8080:80"
      volumes:
          - ./www/docker.local:/var/www/docker.local
          - ./hosts/docker.local:/etc/nginx/conf.d/docker.local.conf
      links:
          - php

  php:
    # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
    build:
      context: .
      dockerfile: ./images/php
    # монтируем директорию с проектами
    volumes:
      - ./www:/var/www